# Generated by Django 5.2 on 2025-05-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='acompanamientos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='acompanamientos_extras',
        ),
        migrations.AddField(
            model_name='acompanamiento',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acompanamientoextra',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
