# Generated by Django 5.2 on 2025-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bebestible_categoria_delete_acompanamientoextra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebestible',
            name='imagen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
