# Generated by Django 5.2 on 2025-05-30 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bebestible_imagen_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.PositiveIntegerField()),
                ('mesa', models.CharField(max_length=20)),
                ('garzon', models.CharField(max_length=100)),
                ('comensales', models.PositiveIntegerField(default=1)),
                ('detalle', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('hora_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_entrega', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
