# Generated by Django 5.2 on 2025-05-31 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='detalle',
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('acompanamientos', models.TextField(blank=True)),
                ('ingredientes', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
            ],
        ),
    ]
